DELETE http://localhost:9191/api/categories/7
X-API-Key: RAHASIA
Accept: application/json
Content-Type: application/json

###
POST http://localhost:9191/api/categories
Content-Type: application/json
Accept: application/json

{
  "name" : 222
}

###
GET http://localhost:9191/api/categories/
X-API-Key: RAHASIA
Accept: application/json
Content-Type: application/json



